<a href="https://colab.research.google.com/github/sauravsapkota378-stack/Concept-and-Technologies-of-AI/blob/main/Workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
from timeit import timeit

def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

Z1 = random.sample(range(1000), 100)
Z2 = random.sample(range(1000), 100)

python_time = timeit("add_python(Z1, Z2)", globals=globals(), number=1000)
numpy_time = timeit("add_numpy(Z1, Z2)", globals=globals(), number=10000)

print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"NumPy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 0.01 s per loop
NumPy addition: 0.14 s per loop


In [ ]:
import numpy as np
import random
from timeit import timeit

# Define addition functions
def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

# Generate larger random sample data
size = 100000 # Increased size for more pronounced difference
Z1_list = random.sample(range(size + 1), size)
Z2_list = random.sample(range(size + 1), size)
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)

# Time the execution of each function
python_time = timeit("add_python(Z1_list, Z2_list)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print results
print(f"Pure Python addition: {python_time:.6f} seconds per loop")
print(f"NumPy addition: {numpy_time:.6f} seconds per loop")

Pure Python addition: 2.274099 seconds per loop
NumPy addition: 0.011068 seconds per loop


In [ ]:
import numpy as np

# Create and display zero , one , and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])

for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")


Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
import numpy as np

zeros_arr = np.zeros((2, 3))
print("A zeros array is\n", zeros_arr, "\nwith dimensions", zeros_arr.shape, "\n")



A zeros array is
 [[0. 0. 0.]
 [0. 0. 0.]] 
with dimensions (2, 3) 



In [ ]:
import numpy as np

array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")


0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array.reshape(3, 2)

print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)


Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [ ]:
import numpy as np

a = np.arange(1, 10)
print(a)

x = range(1, 10)
print(x)
print(list(x))

x = np.arange(10.4)
print(x)

x = np.arange(0.5, 10.4, 0.8)
print(x)


[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
import numpy as np

print(np.linspace(1, 10))
print(np.linspace(1, 10, 7))
print(np.linspace(1, 10, 7, endpoint=False))


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [ ]:
import numpy as np

ones_array = np.ones((2, 3))
zeros_array = np.zeros((3, 2))
empty_array = np.empty((2, 2))
identity_matrix = np.eye(3)

print(ones_array, zeros_array, empty_array, identity_matrix, sep="\n\n")


[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[3.79992666e-315 0.00000000e+000]
 [5.97819431e-322 6.63727098e-310]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

array_from_list = np.array([1, 2, 3])
array_from_tuple = np.array((4, 5, 6))
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]])

print(array_from_list, array_from_tuple, array_from_nested_list, sep="\n")


[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape)

print(arr, zeros, ones, empty, sep="\n")


[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[3.79554325e-315 0.00000000e+000 2.01589600e-312]
 [2.41907520e-312 6.63717843e-310 6.63727323e-310]]


In [ ]:
import numpy as np

array = np.array([1, 2, 3])
new_array = array * 2
copied_array = np.copy(array)
sliced_array = array[1:2]

print("Original array:", array)
print("Multiplied by 2:", new_array)
print("Copied array:", copied_array)
print("Sliced array [1:2]:", sliced_array)


Original array: [1 2 3]
Multiplied by 2: [2 4 6]
Copied array: [1 2 3]
Sliced array [1:2]: [2]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

hstacked = np.hstack((arr1, arr2))
vstacked = np.vstack((arr1, arr2))
colstacked = np.column_stack((arr1[0], arr2[0]))

print(hstacked, vstacked, colstacked, sep="\n")


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concat_axis0 = np.concatenate((arr1, arr2), axis=0)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)

print(concat_axis0, concat_axis1, sep="\n")


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])

print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])


Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Add:", np.add(arr1, arr2))
print("Subtract:", np.subtract(arr1, arr2))
print("Divide:", np.divide(arr1, arr2))
print("Multiply:", np.multiply(arr1, arr2))
print("Power:", np.power(arr1, arr2))
print("Exp:", np.exp(arr1))


Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot)


Result with np.dot:
 [[ 58  64]
 [139 154]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

result_at = A @ B
print("Result with @ operator:\n", result_at)

result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul)


Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])

print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
print("2-Norm (Euclidean):", np.linalg.norm(A))
print("Solution x:", np.linalg.solve(A, B))


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]
